export const countryPhoneCodes = [
  { iso: "AF", code: "+93", name: "Afghanistan" },
  { iso: "AL", code: "+355", name: "Albania" },
  { iso: "DZ", code: "+213", name: "Algeria" },
  { iso: "AD", code: "+376", name: "Andorra" },
  { iso: "AO", code: "+244", name: "Angola" },
  { iso: "AI", code: "+1-264", name: "Anguilla" },
  { iso: "AQ", code: "+672", name: "Antarctica" },
  { iso: "AG", code: "+1-268", name: "Antigua and Barbuda" },
  { iso: "AR", code: "+54", name: "Argentina" },
  { iso: "AM", code: "+374", name: "Armenia" },
  { iso: "AW", code: "+297", name: "Aruba" },
  { iso: "AU", code: "+61", name: "Australia" },
  { iso: "AT", code: "+43", name: "Austria" },
  { iso: "AZ", code: "+994", name: "Azerbaijan" },
  { iso: "BS", code: "+1-242", name: "Bahamas" },
  { iso: "BH", code: "+973", name: "Bahrain" },
  { iso: "BD", code: "+880", name: "Bangladesh" },
  { iso: "BB", code: "+1-246", name: "Barbados" },
  { iso: "BY", code: "+375", name: "Belarus" },
  { iso: "BZ", code: "+501", name: "Belize" },
  { iso: "BJ", code: "+229", name: "Benin" },
  { iso: "BM", code: "+1-441", name: "Bermuda" },
  { iso: "BT", code: "+975", name: "Bhutan" },
  { iso: "BO", code: "+591", name: "Bolivia" },
  { iso: "BA", code: "+387", name: "Bosnia and Herzegovina" },
  { iso: "BW", code: "+267", name: "Botswana" },
  { iso: "BR", code: "+55", name: "Brazil" },
  { iso: "VG", code: "+1-284", name: "British Virgin Islands" },
  { iso: "BN", code: "+673", name: "Brunei" },
  { iso: "BG", code: "+359", name: "Bulgaria" },
  { iso: "BF", code: "+226", name: "Burkina Faso" },
  { iso: "BI", code: "+257", name: "Burundi" },
  { iso: "MM", code: "+95", name: "Myanmar (Burma)" },
  { iso: "KH", code: "+855", name: "Cambodia" },
  { iso: "CM", code: "+237", name: "Cameroon" },
  { iso: "CA", code: "+1", name: "Canada" },
  { iso: "CV", code: "+238", name: "Cape Verde" },
  { iso: "KY", code: "+1-345", name: "Cayman Islands" },
  { iso: "CF", code: "+236", name: "Central African Republic" },
  { iso: "TD", code: "+235", name: "Chad" },
  { iso: "CL", code: "+56", name: "Chile" },
  { iso: "CN", code: "+86", name: "China" },
  { iso: "CO", code: "+57", name: "Colombia" },
  { iso: "KM", code: "+269", name: "Comoros" },
  { iso: "CG", code: "+242", name: "Republic of the Congo" },
  { iso: "CD", code: "+243", name: "DR Congo" },
  { iso: "CK", code: "+682", name: "Cook Islands" },
  { iso: "CR", code: "+506", name: "Costa Rica" },
  { iso: "CI", code: "+225", name: "Cote d'Ivoire" },
  { iso: "HR", code: "+385", name: "Croatia" },
  { iso: "CU", code: "+53", name: "Cuba" },
  { iso: "CW", code: "+599", name: "Curaçao" },
  { iso: "CY", code: "+357", name: "Cyprus" },
  { iso: "CZ", code: "+420", name: "Czechia" },
  { iso: "DK", code: "+45", name: "Denmark" },
  { iso: "DJ", code: "+253", name: "Djibouti" },
  { iso: "DM", code: "+1-767", name: "Dominica" },
  { iso: "DO", code: "+1-809", name: "Dominican Republic" },
  { iso: "DO-2", code: "+1-829", name: "Dominican Republic (Alt)" },
  { iso: "DO-3", code: "+1-849", name: "Dominican Republic (Alt)" },
  { iso: "TL", code: "+670", name: "East Timor" },
  { iso: "EC", code: "+593", name: "Ecuador" },
  { iso: "EG", code: "+20", name: "Egypt" },
  { iso: "SV", code: "+503", name: "El Salvador" },
  { iso: "GQ", code: "+240", name: "Equatorial Guinea" },
  { iso: "ER", code: "+291", name: "Eritrea" },
  { iso: "EE", code: "+372", name: "Estonia" },
  { iso: "SZ", code: "+268", name: "Eswatini" },
  { iso: "ET", code: "+251", name: "Ethiopia" },
  { iso: "FK", code: "+500", name: "Falkland Islands" },
  { iso: "FO", code: "+298", name: "Faroe Islands" },
  { iso: "FJ", code: "+679", name: "Fiji" },
  { iso: "FI", code: "+358", name: "Finland" },
  { iso: "FR", code: "+33", name: "France" },
  { iso: "PF", code: "+689", name: "French Polynesia" },
  { iso: "GA", code: "+241", name: "Gabon" },
  { iso: "GM", code: "+220", name: "Gambia" },
  { iso: "GE", code: "+995", name: "Georgia" },
  { iso: "DE", code: "+49", name: "Germany" },
  { iso: "GH", code: "+233", name: "Ghana" },
  { iso: "GI", code: "+350", name: "Gibraltar" },
  { iso: "GR", code: "+30", name: "Greece" },
  { iso: "GL", code: "+299", name: "Greenland" },
  { iso: "GD", code: "+1-473", name: "Grenada" },
  { iso: "GP", code: "+590", name: "Guadeloupe" },
  { iso: "GU", code: "+1-671", name: "Guam" },
  { iso: "GT", code: "+502", name: "Guatemala" },
  { iso: "GN", code: "+224", name: "Guinea" },
  { iso: "GW", code: "+245", name: "Guinea-Bissau" },
  { iso: "GY", code: "+592", name: "Guyana" },
  { iso: "HT", code: "+509", name: "Haiti" },
  { iso: "HN", code: "+504", name: "Honduras" },
  { iso: "HK", code: "+852", name: "Hong Kong" },
  { iso: "HU", code: "+36", name: "Hungary" },
  { iso: "IS", code: "+354", name: "Iceland" },
  { iso: "IN", code: "+91", name: "India" },
  { iso: "ID", code: "+62", name: "Indonesia" },
  { iso: "IR", code: "+98", name: "Iran" },
  { iso: "IQ", code: "+964", name: "Iraq" },
  { iso: "IE", code: "+353", name: "Ireland" },
  { iso: "IL", code: "+972", name: "Israel" },
  { iso: "IT", code: "+39", name: "Italy" },
  { iso: "JM", code: "+1-876", name: "Jamaica" },
  { iso: "JP", code: "+81", name: "Japan" },
  { iso: "JO", code: "+962", name: "Jordan" },
  { iso: "KZ", code: "+7", name: "Kazakhstan" },
  { iso: "KE", code: "+254", name: "Kenya" },
  { iso: "KI", code: "+686", name: "Kiribati" },
  { iso: "XK", code: "+383", name: "Kosovo" },
  { iso: "KW", code: "+965", name: "Kuwait" },
  { iso: "KG", code: "+996", name: "Kyrgyzstan" },
  { iso: "LA", code: "+856", name: "Laos" },
  { iso: "LV", code: "+371", name: "Latvia" },
  { iso: "LB", code: "+961", name: "Lebanon" },
  { iso: "LS", code: "+266", name: "Lesotho" },
  { iso: "LR", code: "+231", name: "Liberia" },
  { iso: "LY", code: "+218", name: "Libya" },
  { iso: "LI", code: "+423", name: "Liechtenstein" },
  { iso: "LT", code: "+370", name: "Lithuania" },
  { iso: "LU", code: "+352", name: "Luxembourg" },
  { iso: "MO", code: "+853", name: "Macao" },
  { iso: "MK", code: "+389", name: "North Macedonia" },
  { iso: "MG", code: "+261", name: "Madagascar" },
  { iso: "MW", code: "+265", name: "Malawi" },
  { iso: "MY", code: "+60", name: "Malaysia" },
  { iso: "MV", code: "+960", name: "Maldives" },
  { iso: "ML", code: "+223", name: "Mali" },
  { iso: "MT", code: "+356", name: "Malta" },
  { iso: "MH", code: "+692", name: "Marshall Islands" },
  { iso: "MQ", code: "+596", name: "Martinique" },
  { iso: "MR", code: "+222", name: "Mauritania" },
  { iso: "MU", code: "+230", name: "Mauritius" },
  { iso: "YT", code: "+262", name: "Mayotte" },
  { iso: "MX", code: "+52", name: "Mexico" },
  { iso: "FM", code: "+691", name: "Micronesia" },
  { iso: "MD", code: "+373", name: "Moldova" },
  { iso: "MC", code: "+377", name: "Monaco" },
  { iso: "MN", code: "+976", name: "Mongolia" },
  { iso: "ME", code: "+382", name: "Montenegro" },
  { iso: "MS", code: "+1-664", name: "Montserrat" },
  { iso: "MA", code: "+212", name: "Morocco" },
  { iso: "MZ", code: "+258", name: "Mozambique" },
  { iso: "NA", code: "+264", name: "Namibia" },
  { iso: "NR", code: "+674", name: "Nauru" },
  { iso: "NP", code: "+977", name: "Nepal" },
  { iso: "NL", code: "+31", name: "Netherlands" },
  { iso: "NC", code: "+687", name: "New Caledonia" },
  { iso: "NZ", code: "+64", name: "New Zealand" },
  { iso: "NI", code: "+505", name: "Nicaragua" },
  { iso: "NE", code: "+227", name: "Niger" },
  { iso: "NG", code: "+234", name: "Nigeria" },
  { iso: "NU", code: "+683", name: "Niue" },
  { iso: "KP", code: "+850", name: "North Korea" },
  { iso: "NO", code: "+47", name: "Norway" },
  { iso: "OM", code: "+968", name: "Oman" },
  { iso: "PK", code: "+92", name: "Pakistan" },
  { iso: "PW", code: "+680", name: "Palau" },
  { iso: "PS", code: "+970", name: "Palestine" },
  { iso: "PA", code: "+507", name: "Panama" },
  { iso: "PG", code: "+675", name: "Papua New Guinea" },
  { iso: "PY", code: "+595", name: "Paraguay" },
  { iso: "PE", code: "+51", name: "Peru" },
  { iso: "PH", code: "+63", name: "Philippines" },
  { iso: "PL", code: "+48", name: "Poland" },
  { iso: "PT", code: "+351", name: "Portugal" },
  { iso: "PR", code: "+1-787", name: "Puerto Rico" },
  { iso: "PR-2", code: "+1-939", name: "Puerto Rico (Alt)" },
  { iso: "QA", code: "+974", name: "Qatar" },
  { iso: "RE", code: "+262", name: "Reunion" },
  { iso: "RO", code: "+40", name: "Romania" },
  { iso: "RU", code: "+7", name: "Russia" },
  { iso: "RW", code: "+250", name: "Rwanda" },
  { iso: "SH", code: "+290", name: "Saint Helena" },
  { iso: "KN", code: "+1-869", name: "Saint Kitts and Nevis" },
  { iso: "LC", code: "+1-758", name: "Saint Lucia" },
  { iso: "PM", code: "+508", name: "Saint Pierre and Miquelon" },
  { iso: "VC", code: "+1-784", name: "Saint Vincent and the Grenadines" },
  { iso: "WS", code: "+685", name: "Samoa" },
  { iso: "SM", code: "+378", name: "San Marino" },
  { iso: "ST", code: "+239", name: "Sao Tome and Principe" },
  { iso: "SA", code: "+966", name: "Saudi Arabia" },
  { iso: "SN", code: "+221", name: "Senegal" },
  { iso: "RS", code: "+381", name: "Serbia" },
  { iso: "SC", code: "+248", name: "Seychelles" },
  { iso: "SL", code: "+232", name: "Sierra Leone" },
  { iso: "SG", code: "+65", name: "Singapore" },
  { iso: "SK", code: "+421", name: "Slovakia" },
  { iso: "SI", code: "+386", name: "Slovenia" },
  { iso: "SB", code: "+677", name: "Solomon Islands" },
  { iso: "SO", code: "+252", name: "Somalia" },
  { iso: "ZA", code: "+27", name: "South Africa" },
  { iso: "KR", code: "+82", name: "South Korea" },
  { iso: "SS", code: "+211", name: "South Sudan" },
  { iso: "ES", code: "+34", name: "Spain" },
  { iso: "LK", code: "+94", name: "Sri Lanka" },
  { iso: "SD", code: "+249", name: "Sudan" },
  { iso: "SR", code: "+597", name: "Suriname" },
  { iso: "SE", code: "+46", name: "Sweden" },
  { iso: "CH", code: "+41", name: "Switzerland" },
  { iso: "SY", code: "+963", name: "Syria" },
  { iso: "TW", code: "+886", name: "Taiwan" },
  { iso: "TJ", code: "+992", name: "Tajikistan" },
  { iso: "TZ", code: "+255", name: "Tanzania" },
  { iso: "TH", code: "+66", name: "Thailand" },
  { iso: "TG", code: "+228", name: "Togo" },
  { iso: "TK", code: "+690", name: "Tokelau" },
  { iso: "TO", code: "+676", name: "Tonga" },
  { iso: "TT", code: "+1-868", name: "Trinidad and Tobago" },
  { iso: "TN", code: "+216", name: "Tunisia" },
  { iso: "TR", code: "+90", name: "Turkey" },
  { iso: "TM", code: "+993", name: "Turkmenistan" },
  { iso: "TC", code: "+1-649", name: "Turks and Caicos Islands" },
  { iso: "TV", code: "+688", name: "Tuvalu" },
  { iso: "UG", code: "+256", name: "Uganda" },
  { iso: "UA", code: "+380", name: "Ukraine" },
  { iso: "AE", code: "+971", name: "United Arab Emirates" },
  { iso: "GB", code: "+44", name: "United Kingdom" },
  { iso: "US", code: "+1", name: "United States" },
  { iso: "UY", code: "+598", name: "Uruguay" },
  { iso: "VI", code: "+1-340", name: "U.S. Virgin Islands" },
  { iso: "UZ", code: "+998", name: "Uzbekistan" },
  { iso: "VU", code: "+678", name: "Vanuatu" },
  { iso: "VA", code: "+379", name: "Vatican City" },
  { iso: "VE", code: "+58", name: "Venezuela" },
  { iso: "VN", code: "+84", name: "Vietnam" },
  { iso: "YE", code: "+967", name: "Yemen" },
  { iso: "ZM", code: "+260", name: "Zambia" },
  { iso: "ZW", code: "+263", name: "Zimbabwe" }
];
